server:
  port: 8081

spring:
  config:
    import: configserver:http://localhost:8085
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: USERSERVICE
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true 

# eureka: 
#   instance:
#     prefer-ip-address: true
#   client: 
#     fetch-registry: true
#     register-with-eureka: true
#     service-url: 
#       defaultZone: http://localhost:8761/eureka

management:
  health:
    circuitbreaker:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics, circuitbreakers
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      ratingHotelService:
        maxAttempts: 3
        waitDuration: 5s
  rateLimiter:
    instances:
      userRateLimiter:
        limitForPeriod: 2
        limitRefreshPeriod: 4s
        timeoutDuration: 0s
      
      
    
